//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoy.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MedicalOfficer
    {
        public int ID_MedicalOfficer { get; set; }
        public string FName { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public int ID_Gender { get; set; }
        public int ID_Department { get; set; }
        public int ID_Cabinet { get; set; }
        public Nullable<int> ID_Vhod { get; set; }
        public string Smena { get; set; }
        public string StajRaboty { get; set; }
        public string Diplom { get; set; }
        public string Institute { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
        public virtual Department Department { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Vhod Vhod { get; set; }
        public string DepartmentName
        {
            get
            {
                var DepartmentName = helper.GetContext().Department.Where(p => p.ID_Department == this.ID_Department).FirstOrDefault();
                return DepartmentName.Name;
                //if (DepartmentName.Name != "Регистратура")
                // {
                // return DepartmentName.Name;
                // }               
                // else
                // {               
                //     return "";
                // }
            }
        }
        public string GenderName
        {
            get
            {
                var GenderName = helper.GetContext().Gender.Where(p => p.ID_Gender == this.ID_Gender).FirstOrDefault();
                return GenderName.Name;
            }
        }
    }
}
