//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoy.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Patient
    {
        public int ID_Patient { get; set; }
        public string FName { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int ID_Gender { get; set; }
        public string Snils { get; set; }
        public string Pasport { get; set; }
        public int ID_Grajdanstvo { get; set; }
        public int ID_Status { get; set; }
        public string Polis { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Grajdanstvo Grajdanstvo { get; set; }
        public virtual Status Status { get; set; }
        public string GrajdanstvoName
        {
            get
            {
                var GrajdanstvoName = helper.GetContext().Grajdanstvo.Where(p => p.ID_Grajdanstvo == this.ID_Grajdanstvo).FirstOrDefault();
                return GrajdanstvoName.Name;
            }
        }
        public string DateTime
        {
            get
            {
                string dateString = this.DateOfBirth.ToShortDateString();
                {
                    return dateString;
                }

            }
        }
    }
}
